CREATE TABLE IF NOT EXISTS posts (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255),
	text VARCHAR(10000),
	likes INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tags (
	id SERIAL PRIMARY KEY,
	title VARCHAR(63)
);

CREATE TABLE IF NOT EXISTS post_tags (
	post_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,
	FOREIGN KEY (post_id) REFERENCES posts(id),
	FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE IF NOT EXISTS comments (
	id SERIAL PRIMARY KEY,
	text VARCHAR(3000),
	post_id INTEGER NOT NULL,
	FOREIGN KEY (post_id) REFERENCES posts(id),
	likes INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS images (
	id SERIAL PRIMARY KEY,
	data bytea NOT NULL,
	post_id INTEGER NOT NULL,
	FOREIGN KEY (post_id) REFERENCES posts(id)
);