CREATE TABLE IF NOT EXISTS posts (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255),
	text VARCHAR(10000),
	likes_count INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
	id SERIAL PRIMARY KEY,
	title VARCHAR(63) UNIQUE
);

CREATE TABLE IF NOT EXISTS post_tags (
	post_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,
	FOREIGN KEY (post_id) REFERENCES posts(id),
	FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE IF NOT EXISTS comments (
	id INTEGER NOT NULL,
	text VARCHAR(3000),
	post_id INTEGER NOT NULL,
	PRIMARY KEY (post_id, id),
	FOREIGN KEY (post_id) REFERENCES posts(id)
);

CREATE TABLE IF NOT EXISTS images (
	id SERIAL PRIMARY KEY,
	source VARCHAR(3000) NOT NULL,
	post_id INTEGER NOT NULL,
    FOREIGN KEY (post_id) REFERENCES posts(id)
);